### ISSUE TITLE
"Developing" page points to invalid URL

### ISSUE THREAD

**Issue by martynassateika** [stevearc/dql#20]
I wanted to play around with DQL locally, however the link in the "Developing" page seems to go nowhere:

https://dql.readthedocs.io/en/latest/topics/develop.html

**Comment by martynassateika** [comment]
Link in question: https://raw.github.com/stevearc/devbox/master/devbox/unbox.py.

**Comment by stevearc** [comment]
Ah, yeah those docs are hilariously out of date. Let me update them real quick
