### ISSUE TITLE
Feature: Implement `find` OR `search` command which will find tables by name.

### ISSUE THREAD

**Issue by jspreddy** [stevearc/dql#30]
I would like the ability to search for tables matching a certain input string. 
It would be even better if we can use regex as input.

**Proposal:** `find <string|regex>` or `search <string|regex>`
**Output:** The output would be the same as with `ls`, but a shorter list. And maybe coloring the matching part of the table name.
**Note:** This will have to work inside the interactive shell as well as with the option `-c`.

**Workaround:** This is current workaround for not having the built-in functionality.

```
AWS_PROFILE='my-profile' dql -r 'us-east-1' -c "ls" | grep 'word'
```

![shell_magic](https://user-images.githubusercontent.com/2302194/92752830-4b583e00-f357-11ea-8db3-d213e389f0ad.png)

**Comment by stevearc** [comment]
There's already some functionality that enables tab-completion for ls
https://github.com/stevearc/dql/blob/731b50074f62be5bcccb74012c9608c16b9b7444/dql/cli.py#L503-L505

The trick is that you have to run `ls` with no options once before it works. On startup, we don't know anything about what tables may exist and have to wait for that information to get cached.

It wouldn't be too hard to make the `engine.describe` method accept a regex or glob, and then you could do `ls golie*`. Would that do what you want, or do you also want to strip more from the output?

**Comment by jspreddy** [comment]
Unfortunately tab completion while helpful does not meet my needs.
Ideally the matching would be anywhere in the table name not just the begining. `*golie*`

Illustrating what I am looking for:
![match_string_anywhere_in_the_table_name](https://user-images.githubusercontent.com/2302194/92777068-d5ab9c80-f36d-11ea-8446-aa9f867bc4d1.png)

**Comment by jspreddy** [comment]
`ls <glob-pattern>` would work.
