### ISSUE TITLE
`ls` on a table with On-Demand indexes causes `AttributeError`

### ISSUE THREAD

**Issue by jspreddy** [stevearc/dql#34]
## Summary
`ls` on a table which has on-demand indexes fails.
```
> ls golie-on-demand-table
AttributeError: 'GlobalIndex' object has no attribute 'item_count'
```

## DQL Details:
**DQL Version:** 0.5.29-dev0
**Python:** 3.7.7
**OS:** MacOS 10.15.6 (19G2021)

## Table with indexes:
<img width="1334" alt="table-indexes" src="https://user-images.githubusercontent.com/2302194/93671684-1d6bab80-fa73-11ea-8cf7-1e5c03cf6900.png">

## Trace:
<img width="708" alt="pt-1" src="https://user-images.githubusercontent.com/2302194/93671514-a8e43d00-fa71-11ea-9259-7bc1292360ec.png">
<img width="721" alt="pt-2" src="https://user-images.githubusercontent.com/2302194/93671526-bf8a9400-fa71-11ea-8efc-c15add124a27.png">

**Comment by stevearc** [comment]
This was a bug in the dev version of dynamo3. I fixed the problem there and released a new dev build. I also added a snapshot test for `ls <table>` to make sure this is caught in the future, and as a byproduct there's now an easy way to add snapshot tests for commands! Might be useful if you make more changes to the display commands or formats

https://github.com/stevearc/dql/blob/dffa84e11a0c3af7c169159632786c6e6490801c/tests/test_cli.py#L186-L198
