### ISSUE TITLE
Engine: Parse Exception while scanning with attribute_exists operation

### ISSUE THREAD

**Issue by jspreddy** [stevearc/dql#36]
I would assume this to work but it is throwing a `Engine: Parse Exception`.

```sql
scan id, deleted_at from table-name where attribute_exists('deleted_at');
```

**Comment by stevearc** [comment]
If you remove the quotes around `deleted_at` it will parse correctly. I agree that it makes more sense for the attribute to be quoted here so I'll update the parser
