### ISSUE TITLE
Question: Loading dql from a script 

### ISSUE THREAD

**Issue by anandchida** [stevearc/dql#6]
I love this utility! Thank you!

I can load a data.dql file from REPL using file command.
us-east-1> file data.dql
Inserted 1 item

When I attempt to load it from CLI, i'm not sure how to do it.  
$ dql -r us-east-1 -c "file data.dql" 

.. did not work. 

Any help is appreciated.

**Comment by anandchida** [comment]
Couple more questions -
* When creating multiple tables ..
```
$ cat data.dql
CREATE TABLE IF NOT EXISTS city_lookup (city_code STRING HASH KEY, THROUGHPUT (1, 1));
CREATE TABLE IF NOT EXISTS status_lookup (code NUMBER HASH KEY, THROUGHPUT (1, 1));

us-east-1> file test.dql
Created table 'status_lookup'
```
Confirmation message is displayed only for the last created table instead of all tables.

* How do I add comments in my .dql file?

**Comment by stevearc** [comment]
Found the bug, will have a fix out soon.

At the moment multiple statements will only return output for the final statement. I could change that if it's a feature you need, but it'll take a bit of work.

Comments should work the same as normal SQL: `-- comment text appears after two dashes`

**Comment by anandchida** [comment]
This addressed all my issues, thank you!
